services:
  app:
    build: .
    container_name: meobeo-api-dev
    ports:
      - "${APP_PORT}:8000"
    environment:
      - ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/5
      - CELERY_RESULT_BACKEND=redis://redis:6379/5
    env_file:
      - .env
    volumes:
      - ./:/app
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

